//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class admincongifsetting
    {
        public admincongifsetting()
        {
            this.configdetails = new HashSet<configdetail>();
        }
    
        public int adminCongifSettingsId { get; set; }
        public string configName { get; set; }
        public string configValueType { get; set; }
        public string configDiscription { get; set; }
    
        public virtual ICollection<configdetail> configdetails { get; set; }
    }
}
