//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowreturn
    {
        public int borrowReturnId { get; set; }
        public int returnOfBorrowId { get; set; }
        public int borrowLendId { get; set; }
    
        public virtual borrowlend borrowlend { get; set; }
        public virtual returnofborrow returnofborrow { get; set; }
    }
}
