//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowreturnitem
    {
        public int borrowReturnItemsId { get; set; }
        public int returnOfBorrowId { get; set; }
        public int borrowLendStockId { get; set; }
        public Nullable<int> quantityReturn { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual borrowlendstock borrowlendstock { get; set; }
        public virtual returnofborrow returnofborrow { get; set; }
    }
}
