//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowstock
    {
        public int borrowStockId { get; set; }
        public int borrowLendStockId { get; set; }
        public int stockId { get; set; }
    
        public virtual borrowlendstock borrowlendstock { get; set; }
        public virtual stock stock { get; set; }
    }
}
