//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyinfo
    {
        public int companyInfoId { get; set; }
        public string compName { get; set; }
        public string CompWebsite { get; set; }
        public string CompPrintAddress { get; set; }
        public string CompLongAddress { get; set; }
        public string CompContactNo { get; set; }
        public string CompEmailId { get; set; }
        public string CompFootNote1 { get; set; }
        public string CompFootNote2 { get; set; }
        public string prinerType { get; set; }
    }
}
