//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.borrowlends = new HashSet<borrowlend>();
            this.orderpartials = new HashSet<orderpartial>();
            this.orderplaceditems = new HashSet<orderplaceditem>();
        }
    
        public int orderId { get; set; }
        public int orderStatusId { get; set; }
        public string orderNumber { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public int empId { get; set; }
        public int supplierId { get; set; }
        public string statusChangedDiscription { get; set; }
    
        public virtual ICollection<borrowlend> borrowlends { get; set; }
        public virtual employee employee { get; set; }
        public virtual orderstatu orderstatu { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual ICollection<orderpartial> orderpartials { get; set; }
        public virtual ICollection<orderplaceditem> orderplaceditems { get; set; }
    }
}
