//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderpartial
    {
        public orderpartial()
        {
            this.stocks = new HashSet<stock>();
        }
    
        public int orderPartialsId { get; set; }
        public string discription { get; set; }
        public Nullable<System.DateTime> recevingDate { get; set; }
        public int orderId { get; set; }
        public int empId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual order order { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
    }
}
