//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderplaceditem
    {
        public int orderPlacedItemsId { get; set; }
        public int orderId { get; set; }
        public Nullable<int> quantityOrderd { get; set; }
        public int productSuppliedId { get; set; }
        public Nullable<double> ratePrUnit { get; set; }
        public Nullable<int> packSize { get; set; }
    
        public virtual order order { get; set; }
        public virtual productsupplied productsupplied { get; set; }
    }
}
