//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymenttype
    {
        public paymenttype()
        {
            this.sales = new HashSet<sale>();
        }
    
        public short paymentTypeId { get; set; }
        public string paymentTypeName { get; set; }
        public string paymentTypeDisc { get; set; }
    
        public virtual ICollection<sale> sales { get; set; }
    }
}
