//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        public productdetail()
        {
            this.borrowlendstocks = new HashSet<borrowlendstock>();
            this.productsupplieds = new HashSet<productsupplied>();
            this.solditems = new HashSet<solditem>();
        }
    
        public int productDetailId { get; set; }
        public int productId { get; set; }
        public double productSize { get; set; }
        public Nullable<int> alertBFExpiryDays { get; set; }
        public Nullable<int> thresholdLevel { get; set; }
        public string barcode { get; set; }
    
        public virtual ICollection<borrowlendstock> borrowlendstocks { get; set; }
        public virtual product product { get; set; }
        public virtual ICollection<productsupplied> productsupplieds { get; set; }
        public virtual ICollection<solditem> solditems { get; set; }
    }
}
