//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnitem
    {
        public int returnItemsId { get; set; }
        public Nullable<int> quantityReturned { get; set; }
        public Nullable<double> returnAmount { get; set; }
        public int soldItemId { get; set; }
        public int returnOfSalesId { get; set; }
    
        public virtual returnofsale returnofsale { get; set; }
        public virtual solditem solditem { get; set; }
    }
}
