//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnofborrow
    {
        public returnofborrow()
        {
            this.borrowreturns = new HashSet<borrowreturn>();
            this.borrowreturnitems = new HashSet<borrowreturnitem>();
        }
    
        public int returnOfBorrowId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> netAmountReturn { get; set; }
        public int empId { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<borrowreturn> borrowreturns { get; set; }
        public virtual ICollection<borrowreturnitem> borrowreturnitems { get; set; }
        public virtual employee employee { get; set; }
    }
}
