//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnofsale
    {
        public returnofsale()
        {
            this.returnitems = new HashSet<returnitem>();
            this.sales = new HashSet<sale>();
        }
    
        public int returnOfSalesId { get; set; }
        public Nullable<double> amountToReturn { get; set; }
        public string returnType { get; set; }
        public int salesId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> salesmanSaleDayId { get; set; }
    
        public virtual ICollection<returnitem> returnitems { get; set; }
        public virtual sale sale { get; set; }
        public virtual ICollection<sale> sales { get; set; }
        public virtual salesmansaleday salesmansaleday { get; set; }
    }
}
