//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.roleandauthorities = new HashSet<roleandauthority>();
            this.roles1 = new HashSet<role>();
        }
    
        public int rolesId { get; set; }
        public string displayText { get; set; }
        public string actionName { get; set; }
        public string controlerName { get; set; }
        public Nullable<int> parentRolesId { get; set; }
    
        public virtual ICollection<roleandauthority> roleandauthorities { get; set; }
        public virtual ICollection<role> roles1 { get; set; }
        public virtual role role1 { get; set; }
    }
}
