//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public sale()
        {
            this.returnofsales = new HashSet<returnofsale>();
            this.solditems = new HashSet<solditem>();
        }
    
        public int salesId { get; set; }
        public System.DateTime date { get; set; }
        public int empId { get; set; }
        public Nullable<double> saleAmount { get; set; }
        public string salesStatus { get; set; }
        public Nullable<double> discounPercentage { get; set; }
        public Nullable<double> netAmount { get; set; }
        public Nullable<int> patientsId { get; set; }
        public Nullable<int> salesNumber { get; set; }
        public Nullable<int> returnOfSalesId { get; set; }
        public Nullable<short> paymentTypeId { get; set; }
        public Nullable<int> salesmanSaleDayId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual patient patient { get; set; }
        public virtual paymenttype paymenttype { get; set; }
        public virtual ICollection<returnofsale> returnofsales { get; set; }
        public virtual returnofsale returnofsale { get; set; }
        public virtual salesmansaleday salesmansaleday { get; set; }
        public virtual ICollection<solditem> solditems { get; set; }
    }
}
