//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesday
    {
        public salesday()
        {
            this.salesmansaledays = new HashSet<salesmansaleday>();
        }
    
        public int salesDayId { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<int> saleNumber { get; set; }
    
        public virtual ICollection<salesmansaleday> salesmansaledays { get; set; }
    }
}
