//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesmanstatu
    {
        public salesmanstatu()
        {
            this.salesmansaledays = new HashSet<salesmansaleday>();
        }
    
        public string statusName { get; set; }
        public string statusDisc { get; set; }
    
        public virtual ICollection<salesmansaleday> salesmansaledays { get; set; }
    }
}
