//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesmansaleday
    {
        public salesmansaleday()
        {
            this.returnofsales = new HashSet<returnofsale>();
            this.sales = new HashSet<sale>();
        }
    
        public int salesmanSaleDayId { get; set; }
        public Nullable<System.DateTime> dayStartTime { get; set; }
        public Nullable<System.DateTime> dayEndTime { get; set; }
        public Nullable<double> startingAmount { get; set; }
        public Nullable<double> endingAmount { get; set; }
        public string statusName { get; set; }
        public int salesDayId { get; set; }
        public Nullable<int> empId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<returnofsale> returnofsales { get; set; }
        public virtual ICollection<sale> sales { get; set; }
        public virtual salesday salesday { get; set; }
        public virtual salesmanstatu salesmanstatu { get; set; }
    }
}
