//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tobaccocastleEntities : DbContext
    {
        public tobaccocastleEntities()
            : base("name=tobaccocastleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admincongifsetting> admincongifsettings { get; set; }
        public DbSet<authority> authorities { get; set; }
        public DbSet<borrowlend> borrowlends { get; set; }
        public DbSet<borrowlendstatus> borrowlendstatuses { get; set; }
        public DbSet<borrowlendstock> borrowlendstocks { get; set; }
        public DbSet<borrowreturn> borrowreturns { get; set; }
        public DbSet<borrowreturnitem> borrowreturnitems { get; set; }
        public DbSet<borrowstock> borrowstocks { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<companyinfo> companyinfoes { get; set; }
        public DbSet<configdetail> configdetails { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<designation> designations { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employerstock> employerstocks { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<orderpartial> orderpartials { get; set; }
        public DbSet<orderplaceditem> orderplaceditems { get; set; }
        public DbSet<orderstatu> orderstatus { get; set; }
        public DbSet<patient> patients { get; set; }
        public DbSet<paymenttype> paymenttypes { get; set; }
        public DbSet<pharmacylog> pharmacylogs { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productdetail> productdetails { get; set; }
        public DbSet<productsupplied> productsupplieds { get; set; }
        public DbSet<returnitem> returnitems { get; set; }
        public DbSet<returnofborrow> returnofborrows { get; set; }
        public DbSet<returnofsale> returnofsales { get; set; }
        public DbSet<roleandauthority> roleandauthorities { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<salesday> salesdays { get; set; }
        public DbSet<salesmansaleday> salesmansaledays { get; set; }
        public DbSet<salesmanstatu> salesmanstatus { get; set; }
        public DbSet<solditem> solditems { get; set; }
        public DbSet<soldstock> soldstocks { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<user> users { get; set; }
    }
}
