//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class solditem
    {
        public solditem()
        {
            this.returnitems = new HashSet<returnitem>();
            this.soldstocks = new HashSet<soldstock>();
        }
    
        public int soldItemId { get; set; }
        public int quantity { get; set; }
        public Nullable<double> amount { get; set; }
        public int salesId { get; set; }
        public int productDetailId { get; set; }
        public Nullable<double> discountpercent { get; set; }
    
        public virtual productdetail productdetail { get; set; }
        public virtual ICollection<returnitem> returnitems { get; set; }
        public virtual sale sale { get; set; }
        public virtual ICollection<soldstock> soldstocks { get; set; }
    }
}
