//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public stock()
        {
            this.borrowstocks = new HashSet<borrowstock>();
            this.employerstocks = new HashSet<employerstock>();
            this.soldstocks = new HashSet<soldstock>();
        }
    
        public int stockId { get; set; }
        public int productSuppliedId { get; set; }
        public int orderPartialsId { get; set; }
        public double sellingPricePrItem { get; set; }
        public int quantity { get; set; }
        public Nullable<int> itemSold { get; set; }
        public string batchNO { get; set; }
        public System.DateTime expiryDate { get; set; }
        public Nullable<int> quantityReceived { get; set; }
        public Nullable<double> PricePrItem { get; set; }
        public Nullable<double> discountPercentage { get; set; }
        public Nullable<int> packSize { get; set; }
        public string barCode { get; set; }
    
        public virtual ICollection<borrowstock> borrowstocks { get; set; }
        public virtual ICollection<employerstock> employerstocks { get; set; }
        public virtual orderpartial orderpartial { get; set; }
        public virtual productsupplied productsupplied { get; set; }
        public virtual ICollection<soldstock> soldstocks { get; set; }
    }
}
