//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.borrowlends = new HashSet<borrowlend>();
            this.orders = new HashSet<order>();
            this.productsupplieds = new HashSet<productsupplied>();
        }
    
        public int supplierId { get; set; }
        public string supplierName { get; set; }
        public string supplierContactNumber { get; set; }
        public string supplierEmail { get; set; }
        public string manufecture { get; set; }
        public string type { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<borrowlend> borrowlends { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<productsupplied> productsupplieds { get; set; }
    }
}
